# Generated by Django 4.2.1 on 2023-05-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
