# Generated by Django 4.2.1 on 2023-05-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_image_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_active',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
